version: 3
endpoint: "{{HASURA_GRAPHQL_ENDPOINT}}"
metadata_directory: metadata
admin_secret: "{{HASURA_GRAPHQL_ADMIN_SECRET}}"
actions:
  kind: synchronous
  handler_webhook_baseurl: "{{HASURA_ACTION_WEBHOOK}}"
