name: Deploy to Hasura Cloud

on:
  push:
    branches:
      - master

jobs:
  hasura-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Hasura CLI
        run: |
          curl -L https://github.com/hasura/graphql-engine/releases/latest/download/cli-hasura-linux-amd64 --output hasura
          chmod +x hasura
          sudo mv hasura /usr/local/bin/

      - name: Export Env Variables
        run: |
          echo "HASURA_GRAPHQL_ENDPOINT=${{ secrets.HASURA_GRAPHQL_ENDPOINT }}" >> $GITHUB_ENV
          echo "HASURA_GRAPHQL_ADMIN_SECRET=${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}" >> $GITHUB_ENV
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "HASURA_ACTION_WEBHOOK=${{ secrets.HASURA_ACTION_WEBHOOK }}" >> $GITHUB_ENV

      - name: Verify metadata
        run: hasura metadata verify --endpoint "$HASURA_GRAPHQL_ENDPOINT" --admin-secret "$HASURA_GRAPHQL_ADMIN_SECRET"

      - name: Apply migrations
        run: hasura migrate apply --endpoint "$HASURA_GRAPHQL_ENDPOINT" --admin-secret "$HASURA_GRAPHQL_ADMIN_SECRET" --database-name pg-035

      - name: Apply metadata
        run: hasura metadata apply --endpoint "$HASURA_GRAPHQL_ENDPOINT" --admin-secret "$HASURA_GRAPHQL_ADMIN_SECRET"
